version: '3.8'

services:
  liverpool-auto:
    build: .
    container_name: liverpool-auto-app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data/auto
      - ./edge_profile:/data/edge_profile
    environment:
      - WEB_USER=emmanuel
      - WEB_PASS=4mmA180516
      - DOCKER_MODE=true
      - BASE_DIR=/data/auto
      - EDGE_DATA_DIR=/data/edge_profile
    restart: unless-stopped
