"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _dashboard_shell from './dashboard-shell.bones.json'

configureBoneyard({"color":"#242927","animate":"shimmer"})

registerBones({
  "dashboard-shell": _dashboard_shell,
})
